// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `neutron/dex/deposit_record.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:neutron.dex.DepositRecord)
pub struct DepositRecord {
    // message fields
    // @@protoc_insertion_point(field:neutron.dex.DepositRecord.pair_id)
    pub pair_id: ::protobuf::MessageField<super::pair_id::PairID>,
    // @@protoc_insertion_point(field:neutron.dex.DepositRecord.shares_owned)
    pub shares_owned: ::std::string::String,
    // @@protoc_insertion_point(field:neutron.dex.DepositRecord.center_tick_index)
    pub center_tick_index: i64,
    // @@protoc_insertion_point(field:neutron.dex.DepositRecord.lower_tick_index)
    pub lower_tick_index: i64,
    // @@protoc_insertion_point(field:neutron.dex.DepositRecord.upper_tick_index)
    pub upper_tick_index: i64,
    // @@protoc_insertion_point(field:neutron.dex.DepositRecord.fee)
    pub fee: u64,
    // special fields
    // @@protoc_insertion_point(special_field:neutron.dex.DepositRecord.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DepositRecord {
    fn default() -> &'a DepositRecord {
        <DepositRecord as ::protobuf::Message>::default_instance()
    }
}

impl DepositRecord {
    pub fn new() -> DepositRecord {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::pair_id::PairID>(
            "pair_id",
            |m: &DepositRecord| { &m.pair_id },
            |m: &mut DepositRecord| { &mut m.pair_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "shares_owned",
            |m: &DepositRecord| { &m.shares_owned },
            |m: &mut DepositRecord| { &mut m.shares_owned },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "center_tick_index",
            |m: &DepositRecord| { &m.center_tick_index },
            |m: &mut DepositRecord| { &mut m.center_tick_index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "lower_tick_index",
            |m: &DepositRecord| { &m.lower_tick_index },
            |m: &mut DepositRecord| { &mut m.lower_tick_index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "upper_tick_index",
            |m: &DepositRecord| { &m.upper_tick_index },
            |m: &mut DepositRecord| { &mut m.upper_tick_index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "fee",
            |m: &DepositRecord| { &m.fee },
            |m: &mut DepositRecord| { &mut m.fee },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DepositRecord>(
            "DepositRecord",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DepositRecord {
    const NAME: &'static str = "DepositRecord";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pair_id)?;
                },
                18 => {
                    self.shares_owned = is.read_string()?;
                },
                24 => {
                    self.center_tick_index = is.read_int64()?;
                },
                32 => {
                    self.lower_tick_index = is.read_int64()?;
                },
                40 => {
                    self.upper_tick_index = is.read_int64()?;
                },
                48 => {
                    self.fee = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.pair_id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.shares_owned.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.shares_owned);
        }
        if self.center_tick_index != 0 {
            my_size += ::protobuf::rt::int64_size(3, self.center_tick_index);
        }
        if self.lower_tick_index != 0 {
            my_size += ::protobuf::rt::int64_size(4, self.lower_tick_index);
        }
        if self.upper_tick_index != 0 {
            my_size += ::protobuf::rt::int64_size(5, self.upper_tick_index);
        }
        if self.fee != 0 {
            my_size += ::protobuf::rt::uint64_size(6, self.fee);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.pair_id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.shares_owned.is_empty() {
            os.write_string(2, &self.shares_owned)?;
        }
        if self.center_tick_index != 0 {
            os.write_int64(3, self.center_tick_index)?;
        }
        if self.lower_tick_index != 0 {
            os.write_int64(4, self.lower_tick_index)?;
        }
        if self.upper_tick_index != 0 {
            os.write_int64(5, self.upper_tick_index)?;
        }
        if self.fee != 0 {
            os.write_uint64(6, self.fee)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DepositRecord {
        DepositRecord::new()
    }

    fn clear(&mut self) {
        self.pair_id.clear();
        self.shares_owned.clear();
        self.center_tick_index = 0;
        self.lower_tick_index = 0;
        self.upper_tick_index = 0;
        self.fee = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DepositRecord {
        static instance: DepositRecord = DepositRecord {
            pair_id: ::protobuf::MessageField::none(),
            shares_owned: ::std::string::String::new(),
            center_tick_index: 0,
            lower_tick_index: 0,
            upper_tick_index: 0,
            fee: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DepositRecord {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DepositRecord").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DepositRecord {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DepositRecord {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20neutron/dex/deposit_record.proto\x12\x0bneutron.dex\x1a\x14gogopro\
    to/gogo.proto\x1a\x19neutron/dex/pair_id.proto\"\xc9\x02\n\rDepositRecor\
    d\x12,\n\x07pair_id\x18\x01\x20\x01(\x0b2\x13.neutron.dex.PairIDR\x06pai\
    rId\x12x\n\x0cshares_owned\x18\x02\x20\x01(\tR\x0bsharesOwnedBU\xf2\xde\
    \x1f\x13yaml:\"shares_owned\"\xda\xde\x1f&github.com/cosmos/cosmos-sdk/t\
    ypes.Int\xc8\xde\x1f\0\xea\xde\x1f\x0cshares_owned\x12*\n\x11center_tick\
    _index\x18\x03\x20\x01(\x03R\x0fcenterTickIndex\x12(\n\x10lower_tick_ind\
    ex\x18\x04\x20\x01(\x03R\x0elowerTickIndex\x12(\n\x10upper_tick_index\
    \x18\x05\x20\x01(\x03R\x0eupperTickIndex\x12\x10\n\x03fee\x18\x06\x20\
    \x01(\x04R\x03feeB,Z*github.com/neutron-org/neutron/x/dex/typesJ\xfd\x03\
    \n\x06\x12\x04\0\0\x13\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\
    \x02\x12\x03\x01\0\x14\n\x08\n\x01\x08\x12\x03\x03\0A\n\t\n\x02\x08\x0b\
    \x12\x03\x03\0A\n\t\n\x02\x03\0\x12\x03\x04\0\x1e\n\t\n\x02\x03\x01\x12\
    \x03\x05\0#\n\n\n\x02\x04\0\x12\x04\x07\0\x13\x01\n\n\n\x03\x04\0\x01\
    \x12\x03\x07\x08\x15\n\x0b\n\x04\x04\0\x02\0\x12\x03\x08\x02\x15\n\x0c\n\
    \x05\x04\0\x02\0\x06\x12\x03\x08\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\x08\t\x10\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x08\x13\x14\n\x0c\n\
    \x04\x04\0\x02\x01\x12\x04\t\x02\x0e\x1c\n\x0c\n\x05\x04\0\x02\x01\x05\
    \x12\x03\t\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\t\t\x15\n\x0c\n\
    \x05\x04\0\x02\x01\x03\x12\x03\t\x18\x19\n\r\n\x05\x04\0\x02\x01\x08\x12\
    \x04\t\x1a\x0e\x1b\n\x0f\n\x08\x04\0\x02\x01\x08\xee\xfb\x03\x12\x03\n\
    \x1aJ\n\x0f\n\x08\x04\0\x02\x01\x08\xeb\xfb\x03\x12\x03\x0b\x1a[\n\x0f\n\
    \x08\x04\0\x02\x01\x08\xe9\xfb\x03\x12\x03\x0c\x1a8\n\x0f\n\x08\x04\0\
    \x02\x01\x08\xed\xfb\x03\x12\x03\r\x1a>\n\x0b\n\x04\x04\0\x02\x02\x12\
    \x03\x0f\x02\x1e\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0f\x02\x07\n\x0c\
    \n\x05\x04\0\x02\x02\x01\x12\x03\x0f\x08\x19\n\x0c\n\x05\x04\0\x02\x02\
    \x03\x12\x03\x0f\x1c\x1d\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x10\x02\x1d\n\
    \x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x10\x02\x07\n\x0c\n\x05\x04\0\x02\
    \x03\x01\x12\x03\x10\x08\x18\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x10\
    \x1b\x1c\n\x0b\n\x04\x04\0\x02\x04\x12\x03\x11\x02\x1d\n\x0c\n\x05\x04\0\
    \x02\x04\x05\x12\x03\x11\x02\x07\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\
    \x11\x08\x18\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x11\x1b\x1c\n\x0b\n\
    \x04\x04\0\x02\x05\x12\x03\x12\x02\x11\n\x0c\n\x05\x04\0\x02\x05\x05\x12\
    \x03\x12\x02\x08\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x12\t\x0c\n\x0c\n\
    \x05\x04\0\x02\x05\x03\x12\x03\x12\x0f\x10b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::gogo::file_descriptor().clone());
            deps.push(super::pair_id::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(DepositRecord::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
