// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `neutron/dex/limit_order_expiration.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:neutron.dex.LimitOrderExpiration)
pub struct LimitOrderExpiration {
    // message fields
    ///  see limitOrderTranche.proto for details on goodTilDate
    // @@protoc_insertion_point(field:neutron.dex.LimitOrderExpiration.expiration_time)
    pub expiration_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:neutron.dex.LimitOrderExpiration.tranche_ref)
    pub tranche_ref: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:neutron.dex.LimitOrderExpiration.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LimitOrderExpiration {
    fn default() -> &'a LimitOrderExpiration {
        <LimitOrderExpiration as ::protobuf::Message>::default_instance()
    }
}

impl LimitOrderExpiration {
    pub fn new() -> LimitOrderExpiration {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "expiration_time",
            |m: &LimitOrderExpiration| { &m.expiration_time },
            |m: &mut LimitOrderExpiration| { &mut m.expiration_time },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tranche_ref",
            |m: &LimitOrderExpiration| { &m.tranche_ref },
            |m: &mut LimitOrderExpiration| { &mut m.tranche_ref },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LimitOrderExpiration>(
            "LimitOrderExpiration",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LimitOrderExpiration {
    const NAME: &'static str = "LimitOrderExpiration";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.expiration_time)?;
                },
                18 => {
                    self.tranche_ref = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.expiration_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.tranche_ref.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.tranche_ref);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.expiration_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.tranche_ref.is_empty() {
            os.write_bytes(2, &self.tranche_ref)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LimitOrderExpiration {
        LimitOrderExpiration::new()
    }

    fn clear(&mut self) {
        self.expiration_time.clear();
        self.tranche_ref.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LimitOrderExpiration {
        static instance: LimitOrderExpiration = LimitOrderExpiration {
            expiration_time: ::protobuf::MessageField::none(),
            tranche_ref: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LimitOrderExpiration {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LimitOrderExpiration").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LimitOrderExpiration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LimitOrderExpiration {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n(neutron/dex/limit_order_expiration.proto\x12\x0bneutron.dex\x1a\x1fgo\
    ogle/protobuf/timestamp.proto\x1a\x14gogoproto/gogo.proto\"\x86\x01\n\
    \x14LimitOrderExpiration\x12M\n\x0fexpiration_time\x18\x01\x20\x01(\x0b2\
    \x1a.google.protobuf.TimestampR\x0eexpirationTimeB\x08\x90\xdf\x1f\x01\
    \xc8\xde\x1f\0\x12\x1f\n\x0btranche_ref\x18\x02\x20\x01(\x0cR\ntrancheRe\
    fB,Z*github.com/neutron-org/neutron/x/dex/typesJ\xb9\x02\n\x06\x12\x04\0\
    \0\x10\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x01\0\
    \x14\n\x08\n\x01\x08\x12\x03\x03\0A\n\t\n\x02\x08\x0b\x12\x03\x03\0A\n\t\
    \n\x02\x03\0\x12\x03\x04\0)\n\t\n\x02\x03\x01\x12\x03\x06\0\x1e\n\n\n\
    \x02\x04\0\x12\x04\x08\0\x10\x01\n\n\n\x03\x04\0\x01\x12\x03\x08\x08\x1c\
    \nF\n\x04\x04\0\x02\0\x12\x04\n\x02\r1\x1a8\x20see\x20limitOrderTranche.\
    proto\x20for\x20details\x20on\x20goodTilDate\n\n\x0c\n\x05\x04\0\x02\0\
    \x06\x12\x03\n\x02\x1b\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\n\x1c+\n\x0c\
    \n\x05\x04\0\x02\0\x03\x12\x03\n./\n\r\n\x05\x04\0\x02\0\x08\x12\x04\n0\
    \r0\n\x0f\n\x08\x04\0\x02\0\x08\xf2\xfb\x03\x12\x03\x0b/I\n\x0f\n\x08\
    \x04\0\x02\0\x08\xe9\xfb\x03\x12\x03\x0c/K\n\x0b\n\x04\x04\0\x02\x01\x12\
    \x03\x0e\x02\x18\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x0e\x02\x07\n\x0c\
    \n\x05\x04\0\x02\x01\x01\x12\x03\x0e\x08\x13\n\x0c\n\x05\x04\0\x02\x01\
    \x03\x12\x03\x0e\x16\x17b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::gogo::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(LimitOrderExpiration::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
