// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `neutron/dex/trade_pair_id.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:neutron.dex.TradePairID)
pub struct TradePairID {
    // message fields
    // @@protoc_insertion_point(field:neutron.dex.TradePairID.maker_denom)
    pub maker_denom: ::std::string::String,
    // @@protoc_insertion_point(field:neutron.dex.TradePairID.taker_denom)
    pub taker_denom: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:neutron.dex.TradePairID.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TradePairID {
    fn default() -> &'a TradePairID {
        <TradePairID as ::protobuf::Message>::default_instance()
    }
}

impl TradePairID {
    pub fn new() -> TradePairID {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "maker_denom",
            |m: &TradePairID| { &m.maker_denom },
            |m: &mut TradePairID| { &mut m.maker_denom },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "taker_denom",
            |m: &TradePairID| { &m.taker_denom },
            |m: &mut TradePairID| { &mut m.taker_denom },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TradePairID>(
            "TradePairID",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TradePairID {
    const NAME: &'static str = "TradePairID";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                18 => {
                    self.maker_denom = is.read_string()?;
                },
                26 => {
                    self.taker_denom = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.maker_denom.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.maker_denom);
        }
        if !self.taker_denom.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.taker_denom);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.maker_denom.is_empty() {
            os.write_string(2, &self.maker_denom)?;
        }
        if !self.taker_denom.is_empty() {
            os.write_string(3, &self.taker_denom)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TradePairID {
        TradePairID::new()
    }

    fn clear(&mut self) {
        self.maker_denom.clear();
        self.taker_denom.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TradePairID {
        static instance: TradePairID = TradePairID {
            maker_denom: ::std::string::String::new(),
            taker_denom: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TradePairID {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TradePairID").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TradePairID {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TradePairID {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1fneutron/dex/trade_pair_id.proto\x12\x0bneutron.dex\"O\n\x0bTradePa\
    irID\x12\x1f\n\x0bmaker_denom\x18\x02\x20\x01(\tR\nmakerDenom\x12\x1f\n\
    \x0btaker_denom\x18\x03\x20\x01(\tR\ntakerDenomB,Z*github.com/neutron-or\
    g/neutron/x/dex/typesJ\xb7\x01\n\x06\x12\x04\0\0\x08\x01\n\x08\n\x01\x0c\
    \x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x01\0\x14\n\x08\n\x01\x08\x12\
    \x03\x03\0A\n\t\n\x02\x08\x0b\x12\x03\x03\0A\n\n\n\x02\x04\0\x12\x04\x05\
    \0\x08\x01\n\n\n\x03\x04\0\x01\x12\x03\x05\x08\x13\n\x0b\n\x04\x04\0\x02\
    \0\x12\x03\x06\x04\x1b\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x06\x04\n\n\
    \x0c\n\x05\x04\0\x02\0\x01\x12\x03\x06\x0b\x16\n\x0c\n\x05\x04\0\x02\0\
    \x03\x12\x03\x06\x19\x1a\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x07\x04\x1b\n\
    \x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x07\x04\n\n\x0c\n\x05\x04\0\x02\x01\
    \x01\x12\x03\x07\x0b\x16\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x07\x19\
    \x1ab\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(TradePairID::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
