// This file is generated by rust-protobuf 3.1.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `cosmos/base/v1beta1/coin.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_1_0;

///  Coin defines a token with a denomination and an amount.
///
///  NOTE: The amount field is an Int which implements the custom method
///  signatures required by gogoproto.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:cosmos.base.v1beta1.Coin)
pub struct Coin {
    // message fields
    // @@protoc_insertion_point(field:cosmos.base.v1beta1.Coin.denom)
    pub denom: ::std::string::String,
    // @@protoc_insertion_point(field:cosmos.base.v1beta1.Coin.amount)
    pub amount: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:cosmos.base.v1beta1.Coin.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Coin {
    fn default() -> &'a Coin {
        <Coin as ::protobuf::Message>::default_instance()
    }
}

impl Coin {
    pub fn new() -> Coin {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "denom",
            |m: &Coin| { &m.denom },
            |m: &mut Coin| { &mut m.denom },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "amount",
            |m: &Coin| { &m.amount },
            |m: &mut Coin| { &mut m.amount },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Coin>(
            "Coin",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Coin {
    const NAME: &'static str = "Coin";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.denom = is.read_string()?;
                },
                18 => {
                    self.amount = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.denom.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.denom);
        }
        if !self.amount.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.amount);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.denom.is_empty() {
            os.write_string(1, &self.denom)?;
        }
        if !self.amount.is_empty() {
            os.write_string(2, &self.amount)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Coin {
        Coin::new()
    }

    fn clear(&mut self) {
        self.denom.clear();
        self.amount.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Coin {
        static instance: Coin = Coin {
            denom: ::std::string::String::new(),
            amount: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Coin {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Coin").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Coin {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Coin {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  DecCoin defines a token with a denomination and a decimal amount.
///
///  NOTE: The amount field is an Dec which implements the custom method
///  signatures required by gogoproto.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:cosmos.base.v1beta1.DecCoin)
pub struct DecCoin {
    // message fields
    // @@protoc_insertion_point(field:cosmos.base.v1beta1.DecCoin.denom)
    pub denom: ::std::string::String,
    // @@protoc_insertion_point(field:cosmos.base.v1beta1.DecCoin.amount)
    pub amount: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:cosmos.base.v1beta1.DecCoin.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DecCoin {
    fn default() -> &'a DecCoin {
        <DecCoin as ::protobuf::Message>::default_instance()
    }
}

impl DecCoin {
    pub fn new() -> DecCoin {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "denom",
            |m: &DecCoin| { &m.denom },
            |m: &mut DecCoin| { &mut m.denom },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "amount",
            |m: &DecCoin| { &m.amount },
            |m: &mut DecCoin| { &mut m.amount },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DecCoin>(
            "DecCoin",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DecCoin {
    const NAME: &'static str = "DecCoin";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.denom = is.read_string()?;
                },
                18 => {
                    self.amount = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.denom.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.denom);
        }
        if !self.amount.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.amount);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.denom.is_empty() {
            os.write_string(1, &self.denom)?;
        }
        if !self.amount.is_empty() {
            os.write_string(2, &self.amount)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DecCoin {
        DecCoin::new()
    }

    fn clear(&mut self) {
        self.denom.clear();
        self.amount.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DecCoin {
        static instance: DecCoin = DecCoin {
            denom: ::std::string::String::new(),
            amount: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DecCoin {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DecCoin").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DecCoin {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DecCoin {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  IntProto defines a Protobuf wrapper around an Int object.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:cosmos.base.v1beta1.IntProto)
pub struct IntProto {
    // message fields
    // @@protoc_insertion_point(field:cosmos.base.v1beta1.IntProto.int)
    pub int: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:cosmos.base.v1beta1.IntProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a IntProto {
    fn default() -> &'a IntProto {
        <IntProto as ::protobuf::Message>::default_instance()
    }
}

impl IntProto {
    pub fn new() -> IntProto {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "int",
            |m: &IntProto| { &m.int },
            |m: &mut IntProto| { &mut m.int },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<IntProto>(
            "IntProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for IntProto {
    const NAME: &'static str = "IntProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.int = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.int.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.int);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.int.is_empty() {
            os.write_string(1, &self.int)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> IntProto {
        IntProto::new()
    }

    fn clear(&mut self) {
        self.int.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static IntProto {
        static instance: IntProto = IntProto {
            int: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for IntProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("IntProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for IntProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for IntProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  DecProto defines a Protobuf wrapper around a Dec object.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:cosmos.base.v1beta1.DecProto)
pub struct DecProto {
    // message fields
    // @@protoc_insertion_point(field:cosmos.base.v1beta1.DecProto.dec)
    pub dec: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:cosmos.base.v1beta1.DecProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DecProto {
    fn default() -> &'a DecProto {
        <DecProto as ::protobuf::Message>::default_instance()
    }
}

impl DecProto {
    pub fn new() -> DecProto {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "dec",
            |m: &DecProto| { &m.dec },
            |m: &mut DecProto| { &mut m.dec },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DecProto>(
            "DecProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DecProto {
    const NAME: &'static str = "DecProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.dec = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.dec.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.dec);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.dec.is_empty() {
            os.write_string(1, &self.dec)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DecProto {
        DecProto::new()
    }

    fn clear(&mut self) {
        self.dec.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DecProto {
        static instance: DecProto = DecProto {
            dec: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DecProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DecProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DecProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DecProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ecosmos/base/v1beta1/coin.proto\x12\x13cosmos.base.v1beta1\x1a\x14g\
    ogoproto/gogo.proto\"G\n\x04Coin\x12\x14\n\x05denom\x18\x01\x20\x01(\tR\
    \x05denom\x12#\n\x06amount\x18\x02\x20\x01(\tR\x06amountB\x0b\xda\xde\
    \x1f\x03Int\xc8\xde\x1f\0:\x04\xe8\xa0\x1f\x01\"J\n\x07DecCoin\x12\x14\n\
    \x05denom\x18\x01\x20\x01(\tR\x05denom\x12#\n\x06amount\x18\x02\x20\x01(\
    \tR\x06amountB\x0b\xda\xde\x1f\x03Dec\xc8\xde\x1f\0:\x04\xe8\xa0\x1f\x01\
    \")\n\x08IntProto\x12\x1d\n\x03int\x18\x01\x20\x01(\tR\x03intB\x0b\xda\
    \xde\x1f\x03Int\xc8\xde\x1f\0\")\n\x08DecProto\x12\x1d\n\x03dec\x18\x01\
    \x20\x01(\tR\x03decB\x0b\xda\xde\x1f\x03Dec\xc8\xde\x1f\0B,Z\"github.com\
    /cosmos/cosmos-sdk/types\xd8\xe1\x1e\0\x80\xe2\x1e\0J\xb3\n\n\x06\x12\
    \x04\0\0'\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\
    \x01\0\x1c\n\t\n\x02\x03\0\x12\x03\x03\0\x1e\n\x08\n\x01\x08\x12\x03\x05\
    \0O\n\t\n\x02\x08\x0b\x12\x03\x05\0O\n\x08\n\x01\x08\x12\x03\x06\00\n\
    \x0b\n\x04\x08\x9b\xec\x03\x12\x03\x06\00\n\x08\n\x01\x08\x12\x03\x07\00\
    \n\x0b\n\x04\x08\xa0\xec\x03\x12\x03\x07\00\n\xaf\x01\n\x02\x04\0\x12\
    \x04\r\0\x12\x01\x1a\xa2\x01\x20Coin\x20defines\x20a\x20token\x20with\
    \x20a\x20denomination\x20and\x20an\x20amount.\n\n\x20NOTE:\x20The\x20amo\
    unt\x20field\x20is\x20an\x20Int\x20which\x20implements\x20the\x20custom\
    \x20method\n\x20signatures\x20required\x20by\x20gogoproto.\n\n\n\n\x03\
    \x04\0\x01\x12\x03\r\x08\x0c\n\n\n\x03\x04\0\x07\x12\x03\x0e\x02\"\n\r\n\
    \x06\x04\0\x07\x8d\xf4\x03\x12\x03\x0e\x02\"\n\x0b\n\x04\x04\0\x02\0\x12\
    \x03\x10\x02\x14\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x10\x02\x0e\"\n\x0c\n\
    \x05\x04\0\x02\0\x05\x12\x03\x10\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\x10\t\x0e\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x10\x12\x13\n\x0b\n\
    \x04\x04\0\x02\x01\x12\x03\x11\x02S\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\
    \x11\x02\x10\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x11\x02\x08\n\x0c\
    \n\x05\x04\0\x02\x01\x01\x12\x03\x11\t\x0f\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x11\x12\x13\n\x0c\n\x05\x04\0\x02\x01\x08\x12\x03\x11\x14R\n\
    \x0f\n\x08\x04\0\x02\x01\x08\xeb\xfb\x03\x12\x03\x11\x153\n\x0f\n\x08\
    \x04\0\x02\x01\x08\xe9\xfb\x03\x12\x03\x115Q\n\xb9\x01\n\x02\x04\x01\x12\
    \x04\x18\0\x1d\x01\x1a\xac\x01\x20DecCoin\x20defines\x20a\x20token\x20wi\
    th\x20a\x20denomination\x20and\x20a\x20decimal\x20amount.\n\n\x20NOTE:\
    \x20The\x20amount\x20field\x20is\x20an\x20Dec\x20which\x20implements\x20\
    the\x20custom\x20method\n\x20signatures\x20required\x20by\x20gogoproto.\
    \n\n\n\n\x03\x04\x01\x01\x12\x03\x18\x08\x0f\n\n\n\x03\x04\x01\x07\x12\
    \x03\x19\x02\"\n\r\n\x06\x04\x01\x07\x8d\xf4\x03\x12\x03\x19\x02\"\n\x0b\
    \n\x04\x04\x01\x02\0\x12\x03\x1b\x02\x14\n\r\n\x05\x04\x01\x02\0\x04\x12\
    \x04\x1b\x02\x19\"\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\x1b\x02\x08\n\
    \x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x1b\t\x0e\n\x0c\n\x05\x04\x01\x02\0\
    \x03\x12\x03\x1b\x12\x13\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x1c\x02S\n\
    \r\n\x05\x04\x01\x02\x01\x04\x12\x04\x1c\x02\x1b\x14\n\x0c\n\x05\x04\x01\
    \x02\x01\x05\x12\x03\x1c\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\
    \x1c\t\x0f\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x1c\x12\x13\n\x0c\n\
    \x05\x04\x01\x02\x01\x08\x12\x03\x1c\x14R\n\x0f\n\x08\x04\x01\x02\x01\
    \x08\xeb\xfb\x03\x12\x03\x1c\x153\n\x0f\n\x08\x04\x01\x02\x01\x08\xe9\
    \xfb\x03\x12\x03\x1c5Q\nG\n\x02\x04\x02\x12\x04\x20\0\"\x01\x1a;\x20IntP\
    roto\x20defines\x20a\x20Protobuf\x20wrapper\x20around\x20an\x20Int\x20ob\
    ject.\n\n\n\n\x03\x04\x02\x01\x12\x03\x20\x08\x10\n\x0b\n\x04\x04\x02\
    \x02\0\x12\x03!\x02P\n\r\n\x05\x04\x02\x02\0\x04\x12\x04!\x02\x20\x12\n\
    \x0c\n\x05\x04\x02\x02\0\x05\x12\x03!\x02\x08\n\x0c\n\x05\x04\x02\x02\0\
    \x01\x12\x03!\t\x0c\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03!\x0f\x10\n\x0c\
    \n\x05\x04\x02\x02\0\x08\x12\x03!\x11O\n\x0f\n\x08\x04\x02\x02\0\x08\xeb\
    \xfb\x03\x12\x03!\x120\n\x0f\n\x08\x04\x02\x02\0\x08\xe9\xfb\x03\x12\x03\
    !2N\nF\n\x02\x04\x03\x12\x04%\0'\x01\x1a:\x20DecProto\x20defines\x20a\
    \x20Protobuf\x20wrapper\x20around\x20a\x20Dec\x20object.\n\n\n\n\x03\x04\
    \x03\x01\x12\x03%\x08\x10\n\x0b\n\x04\x04\x03\x02\0\x12\x03&\x02P\n\r\n\
    \x05\x04\x03\x02\0\x04\x12\x04&\x02%\x12\n\x0c\n\x05\x04\x03\x02\0\x05\
    \x12\x03&\x02\x08\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03&\t\x0c\n\x0c\n\
    \x05\x04\x03\x02\0\x03\x12\x03&\x0f\x10\n\x0c\n\x05\x04\x03\x02\0\x08\
    \x12\x03&\x11O\n\x0f\n\x08\x04\x03\x02\0\x08\xeb\xfb\x03\x12\x03&\x120\n\
    \x0f\n\x08\x04\x03\x02\0\x08\xe9\xfb\x03\x12\x03&2Nb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::gogo::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(4);
            messages.push(Coin::generated_message_descriptor_data());
            messages.push(DecCoin::generated_message_descriptor_data());
            messages.push(IntProto::generated_message_descriptor_data());
            messages.push(DecProto::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
