// This file is generated by rust-protobuf 3.1.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `interchainqueries/interchainqueries_query.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_1_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:neutron.interchainadapter.interchainqueries.QueryRegisteredQueryResultRequest)
pub struct QueryRegisteredQueryResultRequest {
    // message fields
    // @@protoc_insertion_point(field:neutron.interchainadapter.interchainqueries.QueryRegisteredQueryResultRequest.query_id)
    pub query_id: u64,
    // special fields
    // @@protoc_insertion_point(special_field:neutron.interchainadapter.interchainqueries.QueryRegisteredQueryResultRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a QueryRegisteredQueryResultRequest {
    fn default() -> &'a QueryRegisteredQueryResultRequest {
        <QueryRegisteredQueryResultRequest as ::protobuf::Message>::default_instance()
    }
}

impl QueryRegisteredQueryResultRequest {
    pub fn new() -> QueryRegisteredQueryResultRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "query_id",
            |m: &QueryRegisteredQueryResultRequest| { &m.query_id },
            |m: &mut QueryRegisteredQueryResultRequest| { &mut m.query_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<QueryRegisteredQueryResultRequest>(
            "QueryRegisteredQueryResultRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for QueryRegisteredQueryResultRequest {
    const NAME: &'static str = "QueryRegisteredQueryResultRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.query_id = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.query_id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.query_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.query_id != 0 {
            os.write_uint64(1, self.query_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> QueryRegisteredQueryResultRequest {
        QueryRegisteredQueryResultRequest::new()
    }

    fn clear(&mut self) {
        self.query_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static QueryRegisteredQueryResultRequest {
        static instance: QueryRegisteredQueryResultRequest = QueryRegisteredQueryResultRequest {
            query_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for QueryRegisteredQueryResultRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("QueryRegisteredQueryResultRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for QueryRegisteredQueryResultRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for QueryRegisteredQueryResultRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:neutron.interchainadapter.interchainqueries.QueryRegisteredQueryResultResponse)
pub struct QueryRegisteredQueryResultResponse {
    // message fields
    // @@protoc_insertion_point(field:neutron.interchainadapter.interchainqueries.QueryRegisteredQueryResultResponse.result)
    pub result: ::protobuf::MessageField<super::interchainqueries_tx::QueryResult>,
    // special fields
    // @@protoc_insertion_point(special_field:neutron.interchainadapter.interchainqueries.QueryRegisteredQueryResultResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a QueryRegisteredQueryResultResponse {
    fn default() -> &'a QueryRegisteredQueryResultResponse {
        <QueryRegisteredQueryResultResponse as ::protobuf::Message>::default_instance()
    }
}

impl QueryRegisteredQueryResultResponse {
    pub fn new() -> QueryRegisteredQueryResultResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::interchainqueries_tx::QueryResult>(
            "result",
            |m: &QueryRegisteredQueryResultResponse| { &m.result },
            |m: &mut QueryRegisteredQueryResultResponse| { &mut m.result },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<QueryRegisteredQueryResultResponse>(
            "QueryRegisteredQueryResultResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for QueryRegisteredQueryResultResponse {
    const NAME: &'static str = "QueryRegisteredQueryResultResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.result)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.result.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.result.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> QueryRegisteredQueryResultResponse {
        QueryRegisteredQueryResultResponse::new()
    }

    fn clear(&mut self) {
        self.result.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static QueryRegisteredQueryResultResponse {
        static instance: QueryRegisteredQueryResultResponse = QueryRegisteredQueryResultResponse {
            result: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for QueryRegisteredQueryResultResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("QueryRegisteredQueryResultResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for QueryRegisteredQueryResultResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for QueryRegisteredQueryResultResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n/interchainqueries/interchainqueries_query.proto\x12+neutron.interchai\
    nadapter.interchainqueries\x1a,interchainqueries/interchainqueries_tx.pr\
    oto\">\n!QueryRegisteredQueryResultRequest\x12\x19\n\x08query_id\x18\x01\
    \x20\x01(\x04R\x07queryId\"v\n\"QueryRegisteredQueryResultResponse\x12P\
    \n\x06result\x18\x01\x20\x01(\x0b28.neutron.interchainadapter.interchain\
    queries.QueryResultR\x06resultJ\xe3\x01\n\x06\x12\x04\0\0\x0b\x01\n\x08\
    \n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x01\04\n\t\n\x02\x03\
    \0\x12\x03\x03\06\n\n\n\x02\x04\0\x12\x04\x05\0\x07\x01\n\n\n\x03\x04\0\
    \x01\x12\x03\x05\x08)\n\x0b\n\x04\x04\0\x02\0\x12\x03\x06\x02\x16\n\r\n\
    \x05\x04\0\x02\0\x04\x12\x04\x06\x02\x05+\n\x0c\n\x05\x04\0\x02\0\x05\
    \x12\x03\x06\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x06\t\x11\n\x0c\
    \n\x05\x04\0\x02\0\x03\x12\x03\x06\x14\x15\n\n\n\x02\x04\x01\x12\x04\t\0\
    \x0b\x01\n\n\n\x03\x04\x01\x01\x12\x03\t\x08*\n\x0b\n\x04\x04\x01\x02\0\
    \x12\x03\n\x02\x19\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\n\x02\t,\n\x0c\n\
    \x05\x04\x01\x02\0\x06\x12\x03\n\x02\r\n\x0c\n\x05\x04\x01\x02\0\x01\x12\
    \x03\n\x0e\x14\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\n\x17\x18b\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::interchainqueries_tx::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(QueryRegisteredQueryResultRequest::generated_message_descriptor_data());
            messages.push(QueryRegisteredQueryResultResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
