on:
  push:
    branches:
      - '**'

name: tests

jobs:
  clippy:
    name: Actions - clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          components: clippy
          profile: minimal
          override: true
      - run: cargo fetch --verbose
      - run: cargo clippy --all --all-targets -- -D warnings

  rustfmt:
    name: Actions - rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          components: rustfmt
          profile: minimal
          override: true
      - run: cargo fmt -- --check
  
  checkbuild:
    name: Actions - check artifacts hash sums
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          components: rustfmt
          profile: minimal
          override: true
      - name: Get hash of checksum file
        id: checksum
        run: echo "::set-output name=DATA::$(shasum -a 256 ./artifacts/checksums.txt | cut -f1 -d ' ')"
      - name: Rebuild artifacts
        run: make build_proto && make schema && ./build_release.sh
      - name: Verify
        run: if [[ "${{steps.checksum.outputs.DATA}}" != $(shasum -a 256 ./artifacts/checksums.txt | cut -f1 -d ' ') ]]; then return 2; fi

  unit-test:
    name: Actions - unit test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          profile: minimal
      - run: cargo fetch --verbose
      - run: cargo build
      - run: cargo test --verbose --all
        env:
          RUST_BACKTRACE: 1
